### ISSUE TITLE
Compile Error for Version 0.4.0

### ISSUE THREAD

**Issue by BorisWiegand** [mrapp-ke/Boomer#2]
Hi,

under version 0.4.0 compilation on Windows seems to be impossible. Under Linux I get the following error:

`
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/usr/local/lib/python3.8/site-packages/numpy/core/include -I/usr/local/include/python3.8 -c mlrl/boosting/cython/losses_example_wise.cpp -o build/temp.linux-x86_64-3.8/mlrl/boosting/cython/losses_example_wise.o -fopenmp
 mlrl/boosting/cython/losses_example_wise.cpp:661:10: fatal error: common/measures/measure_evaluation.hpp: No such file or directory
  #include "common/measures/measure_evaluation.hpp"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 compilation terminated.
 error: command 'gcc' failed with exit status 1
`

For more details, I have attached the [execution log](https://github.com/mrapp-ke/Boomer/files/6623730/execution_log.txt).

Perhaps, it might be worth to offer a precompiled version and upload it to pypi?

Do you have any other idea, how I can tackle this issue? 

Thank you very much in advance.

Kind regards

Boris Wiegand

**Comment by mrapp-ke** [comment]
I tried to reproduce the compile error you have encountered by pulling the latest version of the master branch and executing the Makefile. It compiles fine on my Linux machine. 

According to the log that you have attached, the compiler cannot find [this](https://github.com/mrapp-ke/Boomer/blob/978303dcea5b61d1f1cd95094f8ee1acc989b3e7/cpp/subprojects/common/include/common/measures/measure_evaluation.hpp) file. So the first thing to do would be to check if it's actually missing from your local copy of the repository.

If the file is not missing from the file system, the reason for this error might be that the compiler is looking for it in the wrong location. Header files are specified via relative paths. In this case `common/measures/measure_evaluation.hpp`. They are searched for in the root directories given in `setup.py`, which are relative paths themselves:
```
include_dirs = [
    '../cpp/subprojects/common/include',
    '../cpp/subprojects/boosting/include',
    '../cpp/subprojects/seco/include'
]
```
Maybe it helps to use absolute paths in `setup.py`.

> Perhaps, it might be worth to offer a precompiled version and upload it to pypi?

Yes, this would be a reasonable thing to do and it is already planned. But I've not done such thing before and will have to figure out how things are supposed to work first.

**Comment by BorisWiegand** [comment]
I set up a fresh new Ubuntu installation and now it works. Thank you very much for your time and effort.
