### ISSUE TITLE
access the learned rules

### ISSUE THREAD

**Issue by xiaohan2012** [mrapp-ke/Boomer#4]
Hi,

First of all, thanks for this piece of high-quality software!

Second, I'm wondering if there is a way to access the list of learned rules as well as their weights.

Thanks,
Han

**Comment by mrapp-ke** [comment]
Hi,

if you are using the [command line API](https://mlrl-boomer.readthedocs.io/en/latest/testbed/index.html), the arguments `--print-rules true` or `--store-rules true` can be used to output a textual representation of the rules or save it to a text file. The output will include the conditions of each rule (its "body"), as well as its predictions for individual labels (its "head"; this is what you are referring to as "weights").

If you want to access the rules programmatically in your own Python program, you should have a look at the file [`model_characteristics.py`](https://github.com/mrapp-ke/Boomer/blob/master/python/subprojects/testbed/mlrl/testbed/model_characteristics.py). It is used by the command line API to print/store the rules in a model as mentioned above and illustrates how the [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern) can be used to access the rules.

The basic idea is to implement a class that inherits from [`mlrl.common.cython.rule_model.RuleModelVisitor`](https://github.com/mrapp-ke/Boomer/blob/90fc2020cfcbe623173b74bc2e3d6fe797f6f2aa/python/subprojects/common/mlrl/common/cython/rule_model.pyx#L91) (in `model_characteristics.py` this class is called `RuleModelFormatter`). It must implement the following methods:

* `visit_empty_body(EmptyBody)`
* `visit_conjunctive_body(ConjunctiveBody)`
* `visit_complete_head(CompleteHead)`
* `visit_partial_head(PartialHead)`

Here is some example code that illustrates how such a class can be used:

```python
from mlrl.boosting import Boomer
from mlrl.testbed.model_characteristics import RuleModelFormatter

clf = Boomer()  # Create a new estimator
x = [[  1,  2,  3],  # Two training examples with three features
     [ 11, 12, 13]]
y = [[1, 0],  # Ground truth labels of each training example
     [0, 1]]
clf.fit(x, y)
model = clf.model_
visitor = RuleModelFormatter(...)
model.visit(visitor)
```
The `visit` method iterates all rules in the model and, depending on the body and head of each rule, invokes the methods of the `visitor` for each one of them:
* Typically, the first rule is a default rule. It does not contain any conditions in its body and therefore the method `visit_empty_body(EmptyBody)` is called at first. As a default rule predicts for all available labels, its head is passed to the method `visit_complete_head(CompleteHead)`.
* Afterwards, the second rule is accessed. It usually does contain conditions in its body. Therefore the body is passed to the method `visit_conjunctive_body(ConjunctiveBody)`. Afterwards, the rule's head is passed to either one of the methods `visit_complete_head(CompleteHead)` or `visit_partial_head(PartialHead)`, depending on whether the rule predicts for all labels or a single one.
* ...

The thresholds and feature indices of individual conditions, as well as the predictions, are stored in numpy arrays. You should have a look at [`model_characteristics.py`](https://github.com/mrapp-ke/Boomer/blob/master/python/subprojects/testbed/mlrl/testbed/model_characteristics.py) to see how they can be accessed, given an object of type `ConjunctiveBody`, `PartialHead` or `CompleteHead`.
