### ISSUE TITLE
No module named 'mlrl.boosting.cython.learner' 

### ISSUE THREAD

**Issue by xiaohan2012** [mrapp-ke/Boomer#5]
Hi,

When I run 

```python
from mlrl.boosting import Boomer
```

It gives:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hanxiao/code/interpretable-mlc-code/.venv/lib/python3.8/site-packages/mlrl/boosting/__init__.py", line 1, in <module>
    from mlrl.boosting.boosting_learners import Boomer
  File "/Users/hanxiao/code/interpretable-mlc-code/.venv/lib/python3.8/site-packages/mlrl/boosting/boosting_learners.py", line 10, in <module>
    from mlrl.boosting.cython.learner import BoostingRuleLearner as BoostingRuleLearnerWrapper, BoostingRuleLearnerConfig
ModuleNotFoundError: No module named 'mlrl.boosting.cython.learner'
```

My environment:

- MacOS Monterey
- Python 3.8.9, built from Clang 13.0.0 on darwin
- mlrl-boomer==0.8.1
- mlrl-common==0.8.1
- mlrl-testbed==0.8.1

Any idea?

**Comment by mrapp-ke** [comment]
Hi,

did you follow the instructions in the documentation for compiling the library by yourself or did you install it via pip? What command are you using for running your own program? In particular, is it run in the environment where the library was installed?

**Comment by xiaohan2012** [comment]
@mrapp-ke  I used `pip install mlrl-boomer` to install. Should I compile it by myself?

The command I used is `python -c "from mlrl.boosting import Boomer"`, which throws the error described above.

I'm using `virtualenv` and I confirm that the `python` is from the virtualenv. For example, `python -c "import mlrl"` works fine.

**Comment by mrapp-ke** [comment]
I was able to reproduce this issue. It seems like the PyPI packages are currently broken. I will investigate the problem and release a bugfix as soon as possible.

**Comment by mrapp-ke** [comment]
A new release has been pushed to PyPI. Installing the latest packages (version 0.8.2) should solve the problem.
